### PR TITLE
Change default environment variable behaviour

### LINKED ISSUE #45: Create envar file to source
Remove individually setting each envar and source a file instead.

### PR DESCRIPTION
**Pull request by jennviau**
Resolves #45 
* Moves environment variable configuration from `set-env.sh` to `environment-variables` in the root of the repository
* Updates to all scripts to include change
* Updates to documentation for Cluster creation with new tables for variables, including variable name, description and default values
* Adds content to "Before you begin" describing the default cluster deployment configuration, and how to update

### CODE REVIEW

**Comment by knee-berts** [comment]
Prechecks Complete - Ready for review

**Comment by knee-berts** [comment]
Please run the `terraform fmt` command against the **/terraform/cluster_build** directory and then resubmit the Pull Request. It is required that `terraform fmt` be executed against all Terraform configuration files in order to provide consistency across the repo.

**Comment by knee-berts** [comment]
Prechecks Complete - Ready for review

**Comment by jennviau** [comment]
Will re-open

**Pull request closed without merging**
